import axiosClient from "../config/axiosClient";

const createKoi = ({
  name,
  startDate,
  endDate,
  startExhibitionDate,
  endExhibitionDate,
  location,
  description,
  registrationDeadline,
  minParticipants,
  maxParticipants,
  hasGrandChampion,
  hasBestInShow,
  imgUrl,
  registrationFee,
  status,
  createCategorieShowRequests = [],
  createShowStaffRequests = [],
  createShowRuleRequests = [],
  createShowStatusRequests = [],
  createSponsorRequests = [],
  createTicketTypeRequests = [],
}) =>
  axiosClient.post("/koi-show/create", {
    name,
    startDate,
    endDate,
    startExhibitionDate,
    endExhibitionDate,
    location,
    description,
    registrationDeadline,
    minParticipants,
    maxParticipants,
    hasGrandChampion,
    hasBestInShow,
    imgUrl,
    registrationFee,
    status,
    createCategorieShowRequests,
    createShowStaffRequests,
    createShowRuleRequests,
    createShowStatusRequests,
    createSponsorRequests,
    createTicketTypeRequests,
  });

export { createKoi };
