name: Deploy Frontend (Build on VPS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Go to the frontend directory on the VPS
          cd /opt/ksms/frontend

          # --- Build Steps (on the VPS) ---
          # 1. Install Node.js dependencies
          npm ci

          # 2. Build the React application
          npm run build

          # --- Deployment Steps ---
          # Go to the main deployment directory
          cd /opt/ksms

          # Stop and remove the existing frontend container (if any)
          docker compose stop ksms-frontend || true
          docker compose rm -f ksms-frontend || true

          # Start the frontend service (using the pre-built artifacts)
          docker compose up -d --no-deps frontend

          # Health Check
          sleep 5
          curl -s --head http://localhost || echo "Frontend Health check failed"

          echo "✅ Frontend Deployment completed successfully!"