name: Deploy Frontend

on:
  push:
    branches:
      - main  # Chạy khi có commit push lên nhánh main
  workflow_dispatch:  # Cho phép trigger thủ công

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS (SSH)
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Chuyển đến thư mục frontend
          cd /opt/ksms/frontend

          # Kéo mã nguồn mới nhất từ Git
          git pull origin main

          # Cài đặt dependencies
          npm install

          # Build frontend
          npm run build

          # Kiểm tra và khởi động lại dịch vụ hoặc ứng dụng (ví dụ: pm2 cho ứng dụng React)
          if [ -f /opt/ksms/nginx/nginx.conf ]; then
              pm2 restart all || pm2 start npm --name "frontend" -- run start
          else
              echo "nginx.conf không tìm thấy, không thể khởi động lại Nginx"
          fi
