name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      env:
        CI: false
        VITE_API_BASE_URL: https://api.ksms.news
        
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add host to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to VPS
      run: |
        # Tạo thư mục release
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        RELEASE_PATH="/var/www/ksms-frontend/releases/$TIMESTAMP"
        
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo mkdir -p $RELEASE_PATH"
        
        # Copy files
        scp -r ./dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$RELEASE_PATH/
        
        # Update symlink
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "ln -sfn $RELEASE_PATH /var/www/ksms-frontend/current"
        
        # Nginx config đã được cấu hình để phục vụ từ thư mục current
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo nginx -t && sudo systemctl reload nginx"
        
        # Cleanup old releases (keep last 1)
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /var/www/ksms-frontend/releases && ls -t | tail -n +2 | xargs -I {} rm -rf {}"
