name: Frontend CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      REGISTRY_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      BASE_URL: ${{ secrets.BASE_URL }}
      GIT_COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: DockerHub Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}  
      - name: Build and Push Docker Image
        run: docker compose -f docker-compose.build.yaml build --parallel && docker compose -f docker-compose.build.yaml push

  deploy-client:
    name: Deploy Client
    runs-on: self-hosted
    timeout-minutes: 15
    needs: build-client
    env:
      REGISTRY_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      ROOT_DOMAIN: ${{ secrets.ROOT_DOMAIN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: DockerHub Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}  
      - name: Drop Old Container
        run: docker compose -p ksms-application down ksms-client --rmi all -v
      - name: Start new container
        run: docker compose -p ksms-application up ksms-client -d --force-recreate
